In [1]:
# Numpy and pandas
import pandas as pd
import numpy as np

#Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

# Statistics tools
import scipy.stats as stats

# Model prep and Modeling 
from sklearn.decomposition import PCA 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV, ElasticNetCV

# Evaluate
from sklearn.metrics import mean_absolute_error
import statsmodels.api as sm
from statsmodels.tools.eval_measures import mse, rmse

In [6]:
df = pd.read_csv('Features_Variant_1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40948 entries, 0 to 40947
Data columns (total 54 columns):
634995                40948 non-null int64
0                     40948 non-null int64
463                   40948 non-null int64
1                     40948 non-null int64
0.0                   40948 non-null float64
806.0                 40948 non-null float64
11.291044776119403    40948 non-null float64
1.0                   40948 non-null float64
70.49513846124168     40948 non-null float64
0.0.1                 40948 non-null float64
806.0.1               40948 non-null float64
7.574626865671642     40948 non-null float64
0.0.2                 40948 non-null float64
69.435826365571       40948 non-null float64
0.0.3                 40948 non-null float64
76.0                  40948 non-null float64
2.6044776119402986    40948 non-null float64
0.0.4                 40948 non-null float64
8.50550186882253      40948 non-null float64
0.0.5                 40948 non-null float64
806.0.2               40948 non-null float64
10.649253731343284    40948 non-null float64
1.0.1                 40948 non-null float64
70.25478763764251     40948 non-null float64
-69.0                 40948 non-null float64
806.0.3               40948 non-null float64
4.970149253731344     40948 non-null float64
0.0.6                 40948 non-null float64
69.85058043098057     40948 non-null float64
0.1                   40948 non-null int64
0.2                   40948 non-null int64
0.3                   40948 non-null int64
0.4                   40948 non-null int64
0.5                   40948 non-null int64
65                    40948 non-null int64
166                   40948 non-null int64
2                     40948 non-null int64
0.6                   40948 non-null int64
24                    40948 non-null int64
0.7                   40948 non-null int64
0.8                   40948 non-null int64
0.9                   40948 non-null int64
1.1                   40948 non-null int64
0.10                  40948 non-null int64
0.11                  40948 non-null int64
0.12                  40948 non-null int64
0.13                  40948 non-null int64
0.14                  40948 non-null int64
0.15                  40948 non-null int64
0.16                  40948 non-null int64
0.17                  40948 non-null int64
0.18                  40948 non-null int64
1.2                   40948 non-null int64
0.19                  40948 non-null int64
dtypes: float64(25), int64(29)
memory usage: 16.9 MB

In [4]:
test = pd.read_csv('Features_TestSet.csv')
test.head()

,634995,0,463,1,1.0,17.0,7.0,2.0,6.663332499583072,1.0.1,...,0.7,0.8,0.9,0.10,0.11,0.12,1.2,0.13,0.14,1.3
0,634995,0,463,1,1.0,17.0,7.0,2.0,6.663332,1.0,...,0,0,0,0,0,0,0,1,0,0
1,634995,0,463,1,1.0,17.0,7.0,2.0,6.663332,1.0,...,1,0,0,0,0,0,0,1,0,0
2,634995,0,463,1,1.0,17.0,7.0,2.0,6.663332,1.0,...,0,1,1,0,0,0,0,0,0,0
3,634995,0,463,1,1.0,17.0,7.0,2.0,6.663332,1.0,...,0,0,0,1,0,0,0,0,0,1
4,4394623,0,151766,2,1484.0,1484.0,1484.0,1484.0,0.000000,1484.0,...,0,0,0,0,0,0,0,1,0,292

In [7]:
import csv

f = open("Features_Variant_1.csv", "w")
writer = csv.DictWriter(
    f, fieldnames=["Page Popularity/likes", "Page CheckinsÃ¢â‚¬â„¢s ",'Page talking about '])
writer.writeheader()
f.close()

In [8]:
df = pd.read_csv('Features_Variant_1.csv')

In [10]:
df.head()

Empty DataFrame
Columns: [Page Popularity/likes, Page CheckinsÃ¢â‚¬â„¢s , Page talking about ]
Index: []